//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Tb_banners
{
    public int Id { get; set; }
    public string Image1 { get; set; }
    public string Image2 { get; set; }
    public string Image3 { get; set; }
}

public partial class Tb_Category
{
    public Tb_Category()
    {
        this.Tb_Product = new HashSet<Tb_Product>();
    }

    public int Id { get; set; }
    public string Cat_name { get; set; }
    public string Unit { get; set; }
    public Nullable<bool> Status { get; set; }

    public virtual ICollection<Tb_Product> Tb_Product { get; set; }
}

public partial class Tb_login
{
    public int Id { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string UserType { get; set; }
}

public partial class Tb_Order
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Phone_Number { get; set; }
    public string Country { get; set; }
    public string City { get; set; }
    public string Zip_Code { get; set; }
    public string Address { get; set; }
}

public partial class Tb_Product
{
    public int Id { get; set; }
    public string Product_name { get; set; }
    public string Product_Dec { get; set; }
    public string Product_Unit { get; set; }
    public string Product_Price { get; set; }
    public string Product_Image { get; set; }
    public string Product_Image1 { get; set; }
    public string Product_Image2 { get; set; }
    public string Product_Image3 { get; set; }
    public string Product_Image4 { get; set; }
    public Nullable<int> Cat_id { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<System.DateTime> Pro_date { get; set; }
    public Nullable<bool> Our_latest_product { get; set; }
    public Nullable<bool> HomePage { get; set; }
    public Nullable<bool> OurBestProduct { get; set; }
    public Nullable<bool> HomePage2 { get; set; }

    public virtual Tb_Category Tb_Category { get; set; }
}

public partial class Tb_Register
{
    public int Id { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Phone_No { get; set; }
}

public partial class Tb_Signin
{
    public int Id { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Usertype { get; set; }
}
